### ISSUE TITLE
socket.error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Arinerron** [mhassell/gqrx_scan#1]
Hey!

I have remote connection enabled, and yet I get this:

```
Traceback (most recent call last):
  File "gqrx_scan.py", line 123, in <module>
    scanner.scan()
  File "gqrx_scan.py", line 31, in scan
    self._set_freq(freq)
  File "gqrx_scan.py", line 106, in _set_freq
    return self._update("F %s" % freq)
  File "gqrx_scan.py", line 18, in _update
    tn = telnetlib.Telnet(self.host, self.port)
  File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python2.7/telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```

Any ideas?

Thanks.

**Comment by Arinerron** [comment]
Nevermind. Turns out I was confusing the UDP option with TCP.

Thanks a lot for developing this tool, it's pretty awesome.

**Comment by mhassell** [comment]
@Arinerron Thanks for using it and letting me know you like it!  I'd love to develop it more, so if you have any improvements you'd like to make, submit a pull request.
